version: "3"

services:
  frontend:
    build:
      context: ./frontend
      target: DEV
    ports:
      - "3000:3000"
    networks:
      - sample_monorepo
    command: yarn dev
    volumes:
      - .:/src
  backend:
    build:
      context: ./backend
      target: DEV
    ports:
      - "8080:8080"
    networks:
      - sample_monorepo
    command: yarn dev
    volumes:
      - .:/src

networks:
  sample_monorepo:
    driver: bridge
